apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awx
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: awx.shuttle.local
    http:
      paths:
      - path: /
        backend:
          serviceName: awx-web
          servicePort: 80
